// Instance config — eCLLA
// Generated by scripts/instance_creator.py.

window.SITE_CONFIG = (function () {
    const origin = window.location.origin;

    const productionRoots = {
        'https://api.eclla.ecatalogus.ispan.pl': 'https://api.eclla.ecatalogus.ispan.pl',
        'http://api.eclla.ecatalogus.ispan.pl': 'https://api.eclla.ecatalogus.ispan.pl',
        // Public UI: static files hosted by the Henry Bradshaw Society.
        'https://eclla.henrybradshawsociety.org': 'https://api.eclla.ecatalogus.ispan.pl',
    };

    return {
        pageRoot: productionRoots[origin] || origin,
        projectId: 1,
        siteName: 'eCLLA',
        foreign_id_name: 'CLLA no.',
        features: {
            sourceProject: false,
            sourceProjectFilter: false,
            // The original eCLLA was open to anonymous visitors.
            requireLogin: false,
        },
        uiVisibility: {
            menu: {
                about: true,
                manuscripts: true,
                contentAnalysis: true,
                aiTools: true,
            },
            manuscriptFilters: {
                // The original eCLLA offered exactly these three filter tabs ...
                mainInfo: true,
                clla: true,
                content: true,
                // ... and none of the others.
                codicology: false,
                paleography: false,
                layout: false,
                binding: false,
                condition: false,
                musicology: false,
                decoration: false,
                bibliography: false,
                // Main Info showed: name, repository, repository city, dating, digitized.
                // "CLLA no." lives in the CLLA tab, so the generic foreign-id row is hidden.
                repositoryCity: true,
                foreignId: false,
                liturgicalGenre: false,
                shelfmark: false,
                placeOfOrigin: false,
                provenance: false,
                provenanceCountries: false,
                formOfItem: false,
                decorated: false,
                musicNotation: false,
            },
            manuscriptSections: {
                mainInfo: true,
                clla: true,
                codicology: true,
                watermarks: true,
                quires: true,
                layouts: true,
                scripts: true,
                mainHands: true,
                additionHands: true,
                musicNotation: true,
                binding: true,
                decoration: true,
                initials: true,
                miniatures: true,
                bordersOthers: true,
                condition: true,
                content: true,
                history: true,
                originsDating: true,
                provenanceHistory: true,
                bibliography: true,
            },
        },
    };
})();
