// Instance config — MPL Limbo
// Generated by scripts/instance_creator.py.

window.SITE_CONFIG = (function () {
    const origin = window.location.origin;

    const productionRoots = {
        'https://limbo.monumenta-poloniae-liturgica.ispan.pl': 'https://limbo.monumenta-poloniae-liturgica.ispan.pl',
        'http://limbo.monumenta-poloniae-liturgica.ispan.pl': 'https://limbo.monumenta-poloniae-liturgica.ispan.pl',
    };

    return {
        pageRoot: productionRoots[origin] || origin,
        projectId: 2,
        siteName: 'MPL Limbo',
        foreign_id_name: 'MSPL no.',
        features: {
            sourceProject: false,
            sourceProjectFilter: false,
        },
        uiVisibility: {
            menu: {
                about: true,
                manuscripts: true,
                contentAnalysis: true,
                aiTools: true,
            },
            manuscriptFilters: {
                mainInfo: true,
                layout: true,
                binding: true,
                condition: true,
                content: true,
                musicology: true,
                decoration: true,
                bibliography: true,
            },
            manuscriptSections: {
                mainInfo: true,
                clla: true,
                codicology: true,
                watermarks: true,
                quires: true,
                layouts: true,
                scripts: true,
                mainHands: true,
                additionHands: true,
                musicNotation: true,
                binding: true,
                decoration: true,
                initials: true,
                miniatures: true,
                bordersOthers: true,
                condition: true,
                content: true,
                history: true,
                originsDating: true,
                provenanceHistory: true,
                bibliography: true,
            },
        },
    };
})();
