# Generated by Django 6.0.3 on 2026-09-16 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('pipeline_version', models.CharField(default='1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'db_table': 'analysis_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(db_index=True, max_length=128)),
                ('cohort_label', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analysisapp.analysisrun')),
            ],
            options={
                'verbose_name': 'Analysis Artifact',
                'verbose_name_plural': 'Analysis Artifacts',
                'db_table': 'analysis_artifact',
                'ordering': ['cohort', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('run', 'cohort', 'kind'), name='analysis_artifact_uniq')],
            },
        ),
    ]
