#!/usr/bin/env python
"""Convert a pre-UUID (legacy, int-FK) eCatalogus database into the current schema.

Both databases must live on the same MySQL/MariaDB server and be reachable with
the credentials of the configured Django settings module:

  * ``--legacy-db``  the old database restored 1:1 from its SQL dump
  * the Django ``default`` database, freshly created with ``manage.py migrate``
    and still empty (the script refuses to run on a non-empty target unless
    ``--force`` is passed)

What the script does:

  1. copies every non-empty legacy table that has a counterpart in the new
     schema, keeping integer primary keys, renaming columns listed in
     ``COLUMN_RENAMES`` and filling new NOT NULL columns (``entry_date``,
     model defaults such as ``version`` / ``sync_status``),
  2. assigns UUIDs. Rows of the shared dictionaries (ETL categories ``main`` and
     ``shared``) that the master eCatalogus already has get the master's UUID,
     so a later sync does not duplicate them (see ``--reference-db``). Every
     other row gets a deterministic UUID in an eCLLA-specific namespace,
  3. rebuilds every ``*_uuid`` foreign key from the legacy ``*_id`` column,
  4. copies users, groups and group/user permissions (permissions are matched
     by app_label/model/codename, because permission ids differ),
  5. reports dangling legacy foreign keys that could not be resolved and
     compares every converted dictionary row that has a master UUID with the
     master row, column by column.

Tables that are regenerated by Django (content types, permissions, migrations)
or are transient (sessions, captcha, admin log) are skipped.

Usage:

    DJANGO_SETTINGS_MODULE=ecatalogus.settings_eclla \\
        python scripts/convert_legacy_db.py --legacy-db eclla_legacy \\
        --reference-db ecatalogus_master \\
        --uuid-override indexerapp_projects:1=44af92f5b4855fc78e1ae2f10615bab8

``--reference-db`` is a database restored from a *current* dump of the master
eCatalogus. Without it every UUID is generated in the eCLLA namespace and
nothing will line up with the master.
"""

import argparse
import os
import sys
import uuid
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

import django  # noqa: E402


SKIPPED_TABLES = {
    'django_migrations',
    'django_content_type',
    'django_session',
    'django_admin_log',
    'auth_permission',
    'auth_group_permissions',
    'auth_user_user_permissions',
    'captcha_captchastore',
}

# Tables that migrations or the local bootstrap already seed (api_importers
# group, bootstrap admin). Legacy rows win on id/name collisions.
SEEDED_TABLES = {
    'auth_group': ('name',),
    'auth_user': ('username',),
}

# (table, new column) -> legacy column, for columns renamed between versions.
COLUMN_RENAMES = {
    ('content', 'rubric_name_from_ms'): 'rite_name_from_ms',
    ('content', 'subrubric_name_from_ms'): 'subrite_name_from_ms',
    ('content', 'rubric_sequence'): 'rite_sequence',
    ('content', 'rubric_uuid'): 'rite_id',
    ('indexerapp_editioncontent', 'feast_rubric_sequence'): 'feast_rite_sequence',
    ('indexerapp_editioncontent', 'rubric_name_standarized_uuid'): 'rite_name_standarized_id',
}


# Columns never compared with / copied from the master.
VOLATILE_COLUMNS = {'uuid', 'entry_date', 'version'}

# Extra identity for rows whose full content differs from the master's copy in
# harmless ways (e.g. the master filled in an affiliation). Used only when the
# exact-content match fails and the key is unique on both sides.
NATURAL_KEYS = {
    'Contributors': ('initials', 'first_name', 'last_name'),
}

# Master rows were created with uuid5(LEGACY_SYNC_UUID_NAMESPACE, 'model:legacy_pk')
# (etlapp.uuid_utils). Rows that exist only in eCLLA get their own namespace so they
# can never collide with a master UUID that was derived from a different row.
ECLLA_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, 'eclla.ecatalogus.ispan.pl')


def qn(name):
    return f'`{name}`'


def fetch_columns(cursor, schema):
    cursor.execute(
        'SELECT table_name, column_name FROM information_schema.columns WHERE table_schema=%s',
        [schema],
    )
    columns = {}
    for table, column in cursor.fetchall():
        columns.setdefault(table, set()).add(column)
    return columns


def count_rows(cursor, schema, table):
    cursor.execute(f'SELECT COUNT(*) FROM {qn(schema)}.{qn(table)}')
    return cursor.fetchone()[0]


def legacy_column_for(table, new_column, legacy_columns):
    renamed = COLUMN_RENAMES.get((table, new_column))
    if renamed:
        return renamed if renamed in legacy_columns else None
    if new_column in legacy_columns:
        return new_column
    return None


def legacy_fk_column_for(table, field, legacy_columns):
    renamed = COLUMN_RENAMES.get((table, field.column))
    if renamed:
        return renamed if renamed in legacy_columns else None
    if field.column.endswith('_uuid'):
        candidate = field.column[: -len('_uuid')] + '_id'
        if candidate in legacy_columns:
            return candidate
    return None


def assign_uuids(cursor, table, model, reference_db, reference_columns, legacy_table_columns, overrides, stats):
    """Set ``uuid`` for every row of ``table`` (see module docstring, step 2)."""
    from etlapp.model_categories import MODEL_CATEGORIES
    from etlapp.uuid_utils import LEGACY_SYNC_UUID_NAMESPACE

    label = model._meta.label
    pk_column = model._meta.pk.column
    counters = stats.setdefault(label, {})

    def bump(kind):
        counters[kind] = counters.get(kind, 0) + 1

    ref_table_columns = reference_columns.get(table) if reference_db else None
    use_reference = bool(ref_table_columns) and MODEL_CATEGORIES.get(model.__name__) in ('main', 'shared')

    business = []
    reference_rows = {}
    content_index = {}
    key_index = {}
    key_columns = NATURAL_KEYS.get(model.__name__, ())
    if use_reference:
        business = [
            f.column for f in model._meta.concrete_fields
            if not f.primary_key and not f.is_relation
            and f.column not in VOLATILE_COLUMNS and f.column in ref_table_columns
            # Only columns the legacy system had: the master has since filled in newer ones
            # (e.g. formula translations), which must not make a row look different.
            and legacy_column_for(table, f.column, legacy_table_columns) is not None
        ]
        select = ', '.join(qn(c) for c in ['uuid', *business])
        cursor.execute(f'SELECT {select} FROM {qn(reference_db)}.{qn(table)} WHERE uuid IS NOT NULL')
        for row in cursor.fetchall():
            reference_rows[row[0]] = row[1:]
            content_index.setdefault(row[1:], []).append(row[0])
            if key_columns:
                key = tuple(row[1 + business.index(c)] for c in key_columns)
                key_index.setdefault(key, []).append(row[0])

    select = ', '.join(qn(c) for c in [pk_column, *business])
    cursor.execute(f'SELECT {select} FROM {qn(table)} WHERE uuid IS NULL ORDER BY {qn(pk_column)}')
    local_rows = cursor.fetchall()

    used = set(overrides.get((table, row[0])) for row in local_rows) - {None}
    updates = []
    for row in local_rows:
        pk, content = row[0], tuple(row[1:])
        chosen = overrides.get((table, pk))
        if chosen:
            bump('override')
        elif use_reference:
            candidate = uuid.uuid5(LEGACY_SYNC_UUID_NAMESPACE, f'{label}:{pk}').hex
            if candidate in reference_rows and candidate not in used:
                same = reference_rows[candidate] == content
                # Rows made only of foreign keys have no content to compare.
                ambiguous = len(content_index.get(content, [])) > 1
                if same or ambiguous:
                    chosen = candidate
                    bump('master_uuid5' if same and not ambiguous else 'master_uuid5_unverified')
            if chosen is None:
                matches = [u for u in content_index.get(content, []) if u not in used]
                if len(matches) == 1 and len(content_index[content]) == 1:
                    chosen = matches[0]
                    bump('master_content')
            if chosen is None and key_columns:
                key = tuple(content[business.index(c)] for c in key_columns)
                matches = [u for u in key_index.get(key, []) if u not in used]
                if len(matches) == 1 and len(key_index[key]) == 1:
                    chosen = matches[0]
                    bump('master_natural_key')
        if chosen is None:
            chosen = uuid.uuid5(ECLLA_NAMESPACE, f'{label}:{pk}').hex
            bump('eclla_only')
        used.add(chosen)
        updates.append((chosen, pk))
    cursor.executemany(f'UPDATE {qn(table)} SET uuid=%s WHERE {qn(pk_column)}=%s', updates)


def verify_against_reference(cursor, models_by_table, tables, reference_db, reference_columns, target_columns, legacy_columns):
    """Compare converted rows that carry a master UUID with the master's rows."""
    from etlapp.model_categories import MODEL_CATEGORIES

    problems = []
    for table in tables:
        model = models_by_table.get(table)
        if model is None or MODEL_CATEGORIES.get(model.__name__) not in ('main', 'shared'):
            continue
        if table not in reference_columns or 'uuid' not in target_columns[table]:
            continue
        compared = [
            f.column for f in model._meta.concrete_fields
            if not f.primary_key and f.column not in VOLATILE_COLUMNS
            and f.column in reference_columns[table] and f.column in target_columns[table]
            and (
                legacy_column_for(table, f.column, legacy_columns[table]) is not None
                or legacy_fk_column_for(table, f, legacy_columns[table]) is not None
            )
        ]
        cursor.execute(
            f'SELECT COUNT(*) FROM {qn(table)} t JOIN {qn(reference_db)}.{qn(table)} r ON r.uuid = t.uuid'
        )
        shared_rows = cursor.fetchone()[0]
        for column in compared:
            cursor.execute(
                f'SELECT COUNT(*) FROM {qn(table)} t JOIN {qn(reference_db)}.{qn(table)} r ON r.uuid = t.uuid '
                f'WHERE NOT (t.{qn(column)} <=> r.{qn(column)})'
            )
            different = cursor.fetchone()[0]
            if different:
                problems.append((table, column, different, shared_rows))
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--legacy-db', required=True, help='Name of the restored legacy database.')
    parser.add_argument(
        '--uuid-override',
        action='append',
        default=[],
        metavar='TABLE:PK=UUID',
        help='Force a UUID for one row, e.g. to align a project with the master instance.',
    )
    parser.add_argument(
        '--reference-db',
        help='Database restored from a current dump of the master eCatalogus; dictionary rows it '
             'already has keep the master UUIDs.',
    )
    parser.add_argument('--force', action='store_true', help='Run even if the target already contains data.')
    args = parser.parse_args()

    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ecatalogus.settings')
    django.setup()

    from django.apps import apps
    from django.db import connection, transaction
    from django.utils import timezone

    legacy = args.legacy_db
    target = connection.settings_dict['NAME']
    if legacy == target:
        sys.exit('Legacy and target database must differ.')

    overrides = {}
    for raw in args.uuid_override:
        table_pk, value = raw.split('=', 1)
        table, pk = table_pk.split(':', 1)
        overrides[(table, int(pk))] = uuid.UUID(value).hex

    cursor = connection.cursor()
    legacy_columns = fetch_columns(cursor, legacy)
    target_columns = fetch_columns(cursor, target)
    if not legacy_columns:
        sys.exit(f'Legacy database {legacy!r} is empty or not accessible.')

    reference_columns = fetch_columns(cursor, args.reference_db) if args.reference_db else {}
    if args.reference_db and not reference_columns:
        sys.exit(f'Reference database {args.reference_db!r} is empty or not accessible.')

    models_by_table = {model._meta.db_table: model for model in apps.get_models()}
    tables = []
    for table in sorted(legacy_columns):
        if table in SKIPPED_TABLES or table not in target_columns:
            continue
        if count_rows(cursor, legacy, table) == 0:
            continue
        tables.append(table)

    if not args.force:
        non_empty = [t for t in tables if t not in SEEDED_TABLES and count_rows(cursor, target, t)]
        if non_empty:
            sys.exit(f'Target database is not empty ({", ".join(non_empty)}). Use --force to continue.')

    now = timezone.now().replace(tzinfo=None)
    report = {}
    dangling = []

    with transaction.atomic():
        cursor.execute('SET FOREIGN_KEY_CHECKS=0')

        for table, unique_columns in SEEDED_TABLES.items():
            if table not in tables:
                continue
            conditions = ' OR '.join(
                f'{qn(c)} IN (SELECT {qn(c)} FROM {qn(legacy)}.{qn(table)})' for c in ('id', *unique_columns)
            )
            cursor.execute(f'SELECT id FROM {qn(table)} WHERE {conditions}')
            colliding_ids = [row[0] for row in cursor.fetchall()]
            if colliding_ids:
                print(f'{table}: replacing seeded rows {colliding_ids} with legacy rows')
                placeholders = ', '.join(['%s'] * len(colliding_ids))
                owner = 'group_id' if table == 'auth_group' else 'user_id'
                for link_table in ('auth_user_groups', f'{table}_permissions' if table == 'auth_group' else 'auth_user_user_permissions'):
                    cursor.execute(f'DELETE FROM {qn(link_table)} WHERE {owner} IN ({placeholders})', colliding_ids)
                cursor.execute(f'DELETE FROM {qn(table)} WHERE id IN ({placeholders})', colliding_ids)

        # Phase 1: copy rows and plain columns.
        for table in tables:
            model = models_by_table.get(table)
            fields_by_column = {f.column: f for f in model._meta.concrete_fields} if model else {}
            insert_columns, select_exprs, params = [], [], []

            for column in sorted(target_columns[table]):
                field = fields_by_column.get(column)
                if field is not None and field.is_relation and field.many_to_one and column.endswith('_uuid'):
                    continue  # rebuilt in phase 3
                if column == 'uuid' and model is not None:
                    continue  # assigned in phase 2

                source = legacy_column_for(table, column, legacy_columns[table])
                if source is not None:
                    insert_columns.append(column)
                    if field is not None and not field.null and field.has_default():
                        # Nullable in the legacy schema, NOT NULL now.
                        select_exprs.append(f'COALESCE(o.{qn(source)}, %s)')
                        params.append(field.get_db_prep_save(field.get_default(), connection))
                    else:
                        select_exprs.append(f'o.{qn(source)}')
                    continue

                if field is None or field.null:
                    continue
                if getattr(field, 'auto_now', False) or getattr(field, 'auto_now_add', False):
                    value = now
                elif field.has_default():
                    value = field.get_db_prep_save(field.get_default(), connection)
                else:
                    sys.exit(f'{table}.{column} is NOT NULL without a default and has no legacy source.')
                insert_columns.append(column)
                select_exprs.append('%s')
                params.append(value)

            cursor.execute(
                f'INSERT INTO {qn(table)} ({", ".join(qn(c) for c in insert_columns)}) '
                f'SELECT {", ".join(select_exprs)} FROM {qn(legacy)}.{qn(table)} o',
                params,
            )
            report[table] = cursor.rowcount

        # Phase 2: UUIDs.
        uuid_stats = {}
        for table in tables:
            model = models_by_table.get(table)
            if model is None or 'uuid' not in target_columns[table]:
                continue
            assign_uuids(
                cursor, table, model, args.reference_db, reference_columns, legacy_columns[table], overrides, uuid_stats
            )

        # Phase 3: UUID foreign keys from legacy int foreign keys.
        for table in tables:
            model = models_by_table.get(table)
            if model is None:
                continue
            pk_column = model._meta.pk.column
            for field in model._meta.concrete_fields:
                if not (field.is_relation and field.many_to_one and field.column.endswith('_uuid')):
                    continue
                legacy_fk = legacy_fk_column_for(table, field, legacy_columns[table])
                if legacy_fk is None:
                    continue
                parent = field.related_model._meta
                cursor.execute(
                    f'UPDATE {qn(table)} n '
                    f'JOIN {qn(legacy)}.{qn(table)} o ON o.{qn(pk_column)} = n.{qn(pk_column)} '
                    f'JOIN {qn(parent.db_table)} p ON p.{qn(parent.pk.column)} = o.{qn(legacy_fk)} '
                    f'SET n.{qn(field.column)} = p.{qn(field.target_field.column)}'
                )
                cursor.execute(
                    f'SELECT o.{qn(pk_column)}, o.{qn(legacy_fk)} FROM {qn(legacy)}.{qn(table)} o '
                    f'JOIN {qn(table)} n ON n.{qn(pk_column)} = o.{qn(pk_column)} '
                    f'WHERE o.{qn(legacy_fk)} IS NOT NULL AND n.{qn(field.column)} IS NULL'
                )
                for pk, value in cursor.fetchall():
                    dangling.append(f'{table}[{pk}].{legacy_fk}={value} -> {parent.db_table} (missing)')

        # Phase 4: permissions, matched by natural key.
        for table, owner in (('auth_group_permissions', 'group_id'), ('auth_user_user_permissions', 'user_id')):
            cursor.execute(
                f'INSERT INTO {qn(table)} ({owner}, permission_id) '
                f'SELECT o.{owner}, np.id FROM {qn(legacy)}.{qn(table)} o '
                f'JOIN {qn(legacy)}.auth_permission op ON op.id = o.permission_id '
                f'JOIN {qn(legacy)}.django_content_type oct ON oct.id = op.content_type_id '
                f'JOIN django_content_type nct ON nct.app_label = oct.app_label AND nct.model = oct.model '
                f'JOIN auth_permission np ON np.content_type_id = nct.id AND np.codename = op.codename'
            )
            report[table] = cursor.rowcount

        cursor.execute('SET FOREIGN_KEY_CHECKS=1')

        problems = []
        if args.reference_db:
            problems = verify_against_reference(
                cursor, models_by_table, tables, args.reference_db, reference_columns, target_columns, legacy_columns
            )

    for table, rows in report.items():
        print(f'{table}: {rows}')
    print('\nUUID assignment (per model):')
    for label, counters in sorted(uuid_stats.items()):
        print(f'  {label:36} ' + ', '.join(f'{k}={v}' for k, v in sorted(counters.items())))
    if args.reference_db:
        if problems:
            print(f'\n{len(problems)} columns differ from the master for rows sharing a UUID:')
            for table, column, different, total in problems:
                print(f'  {table}.{column}: {different} of {total} rows')
        else:
            print('\nAll converted rows that share a UUID with the master match it in every column.')
    if dangling:
        print(f'\n{len(dangling)} dangling legacy foreign keys (left NULL):')
        for line in dangling:
            print(f'  {line}')
    print('\nDone.')


if __name__ == '__main__':
    main()
