# Generated by Django 6.0.3 on 2026-03-04 15:24

import django.core.validators
import django.db.models.deletion
import indexerapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('shortname', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('zotero_id', models.CharField(blank=True, max_length=128, null=True)),
                ('hierarchy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bibliography',
                'db_table': 'bibliography',
            },
        ),
        migrations.CreateModel(
            name='BindingComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Binding Components',
                'db_table': 'binding_components',
            },
        ),
        migrations.CreateModel(
            name='BindingDecorationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Binding Decoration Types',
                'db_table': 'binding_decoration_types',
            },
        ),
        migrations.CreateModel(
            name='BindingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Binding Materials',
                'db_table': 'binding_materials',
            },
        ),
        migrations.CreateModel(
            name='BindingStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Binding Styles',
                'db_table': 'binding_styles',
            },
        ),
        migrations.CreateModel(
            name='BindingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Binding Types',
                'db_table': 'binding_types',
            },
        ),
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('latin_keywords', models.CharField(blank=True, max_length=400)),
                ('short_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ceremony',
                'verbose_name_plural': 'Ceremonies',
                'db_table': 'ceremony',
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Characteristics',
                'db_table': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contributors',
                'db_table': 'contributors',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, choices=[('T', 'temporal'), ('S', 'sanctoral')], max_length=2, null=True)),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=65, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Days',
                'db_table': 'day',
            },
        ),
        migrations.CreateModel(
            name='DecorationTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Decoration Techniques',
                'db_table': 'decoration_techniques',
            },
        ),
        migrations.CreateModel(
            name='FeastRanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Feast Ranks',
                'db_table': 'feast_ranks',
            },
        ),
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('translation_en', models.TextField(blank=True, null=True)),
                ('translation_pl', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Formulas',
                'db_table': 'formulas',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=28, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Hands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rism', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_identified', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Hands',
                'db_table': 'hands',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Layers',
                'db_table': 'layer',
            },
        ),
        migrations.CreateModel(
            name='LiturgicalGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Liturgical Genres',
                'db_table': 'liturgical_genres',
            },
        ),
        migrations.CreateModel(
            name='MassHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Mass/Hours',
                'db_table': 'mass_hour',
            },
        ),
        migrations.CreateModel(
            name='MusicNotationNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Music Notation Names',
                'db_table': 'music_notation_names',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('place_type', models.CharField(blank=True, choices=[('library', 'library'), ('center', 'center'), ('scriptory', 'scriptory'), ('multiple', 'multiple')], max_length=10, null=True)),
                ('country_today_eng', models.CharField(blank=True, max_length=64, null=True)),
                ('region_today_eng', models.CharField(blank=True, max_length=64, null=True)),
                ('city_today_eng', models.CharField(blank=True, max_length=64, null=True)),
                ('repository_today_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('country_today_local_language', models.CharField(blank=True, max_length=64, null=True)),
                ('region_today_local_language', models.CharField(blank=True, max_length=64, null=True)),
                ('city_today_local_language', models.CharField(blank=True, max_length=64, null=True)),
                ('repository_today_local_language', models.CharField(blank=True, max_length=255, null=True)),
                ('country_historic_eng', models.CharField(blank=True, max_length=64, null=True)),
                ('region_historic_eng', models.CharField(blank=True, max_length=64, null=True)),
                ('city_historic_eng', models.CharField(blank=True, max_length=64, null=True)),
                ('repository_historic_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('country_historic_local_language', models.CharField(blank=True, max_length=64, null=True)),
                ('region_historic_local_language', models.CharField(blank=True, max_length=64, null=True)),
                ('city_historic_local_language', models.CharField(blank=True, max_length=64, null=True)),
                ('repository_historic_local_language', models.CharField(blank=True, max_length=255, null=True)),
                ('country_historic_latin', models.CharField(blank=True, max_length=64, null=True)),
                ('region_historic_latin', models.CharField(blank=True, max_length=64, null=True)),
                ('city_historic_latin', models.CharField(blank=True, max_length=64, null=True)),
                ('repository_historic_latin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Places',
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Name', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ScriptNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Script Names',
                'db_table': 'names',
            },
        ),
        migrations.CreateModel(
            name='SeasonMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('kind', models.CharField(blank=True, choices=[('S', 'season'), ('M', 'month')], max_length=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Seasons/Months',
                'db_table': 'season_month',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TimeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_description', models.CharField(max_length=64)),
                ('century_from', models.IntegerField()),
                ('century_to', models.IntegerField()),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Time References',
                'db_table': 'time_reference',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.TextField(default='')),
                ('result', models.TextField(default='')),
                ('error', models.TextField(default='')),
                ('execution_time', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bibliography')),
            ],
            options={
                'verbose_name_plural': 'Attribute Debate',
                'db_table': 'attribute_debate',
            },
        ),
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rgb', models.CharField(blank=True, max_length=8, null=True)),
                ('parent_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.colours')),
            ],
            options={
                'verbose_name_plural': 'Colours',
                'db_table': 'colours',
            },
        ),
        migrations.CreateModel(
            name='ContentFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.contentfunctions')),
            ],
            options={
                'verbose_name_plural': 'Content functions',
                'db_table': 'content_functions',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_name_from_ms', models.CharField(blank=True, max_length=1024, null=True)),
                ('subrubric_name_from_ms', models.TextField(blank=True, null=True)),
                ('rubric_sequence', models.PositiveIntegerField(blank=True, default=indexerapp.models.Content.calc_last_sequence, null=True)),
                ('formula_text', models.TextField(blank=True, null=True)),
                ('sequence_in_ms', models.PositiveIntegerField(blank=True, default=indexerapp.models.Content.calc_last_sequence, null=True)),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('original_or_added', models.CharField(blank=True, choices=[('ORIGINAL', 'original'), ('ADDED', 'added')], max_length=10, null=True)),
                ('biblical_reference', models.CharField(blank=True, max_length=31, null=True)),
                ('reference_to_other_items', models.CharField(blank=True, max_length=127, null=True)),
                ('similarity_by_user', models.CharField(blank=True, choices=[('0', 'the formula not in the editions'), ('0.5', 'paraphrase'), ('1', 'exact match')], max_length=4, null=True)),
                ('proper_texts', models.BooleanField(blank=True, null=True)),
                ('similarity_levenshtein', models.FloatField(blank=True, null=True)),
                ('similarity_levenshtein_percent', models.FloatField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('edition_subindex', models.CharField(blank=True, max_length=1024, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_main_function', to='indexerapp.contentfunctions')),
                ('subfunction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sub_function', to='indexerapp.contentfunctions')),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_day', to='indexerapp.day')),
            ],
            options={
                'verbose_name_plural': 'Content',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('latin_name', models.CharField(max_length=128, verbose_name='Latin name of the date from ms')),
                ('feast_name', models.CharField(max_length=128, verbose_name='feast name')),
                ('rubricated', models.BooleanField(blank=True, null=True)),
                ('littera_dominicalis', models.CharField(max_length=2)),
                ('aureus_numerus', models.IntegerField(blank=True, null=True)),
                ('aureus_numerus_roman', models.CharField(blank=True, max_length=20, null=True)),
                ('other_remarks', models.CharField(blank=True, max_length=128, null=True, verbose_name='other remarks from ms')),
                ('original', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_content', to='indexerapp.content', verbose_name='Content (if present)')),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('feast_rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_feast', to='indexerapp.feastranks', verbose_name='Rank of the feast')),
            ],
            options={
                'verbose_name_plural': 'Calendar',
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_or_added', models.CharField(blank=True, choices=[('ORIGINAL', 'original'), ('ADDED', 'added')], max_length=10, null=True)),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('location_on_the_page', models.CharField(blank=True, choices=[('WITHIN', 'within the column'), ('MARGIN', 'on the margin'), ('IN_TEXT', 'in the text line')], max_length=10, null=True)),
                ('size_characteristic', models.CharField(blank=True, choices=[('SMALL', 'small'), ('1LINE', '1-line'), ('2LINES', '2-lines'), ('3LINES', '3-lines'), ('1SYSTEM', '1-system'), ('2SYSTEMS', '2-systems'), ('LARGE', 'large'), ('FULL', 'full page')], max_length=10, null=True)),
                ('size_height_min', models.PositiveIntegerField(blank=True, null=True)),
                ('size_height_max', models.PositiveIntegerField(blank=True, null=True)),
                ('size_width_min', models.PositiveIntegerField(blank=True, null=True)),
                ('size_width_max', models.PositiveIntegerField(blank=True, null=True)),
                ('monochrome_or_colour', models.CharField(blank=True, choices=[('M', 'monochromatic'), ('B', 'bicolored'), ('C', 'multicolored')], max_length=2, null=True)),
                ('ornamented_text', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_decoration', to='indexerapp.calendar')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_decoration', to='indexerapp.content')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_technique', to='indexerapp.decorationtechniques')),
            ],
            options={
                'verbose_name_plural': 'Decoration',
                'db_table': 'decoration',
            },
        ),
        migrations.CreateModel(
            name='DecorationCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_characteristics', to='indexerapp.characteristics')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_characteristics', to='indexerapp.decoration')),
            ],
            options={
                'verbose_name_plural': 'Decoration characteristics',
                'db_table': 'decoration_characteristics',
            },
        ),
        migrations.CreateModel(
            name='DecorationColours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_colour', to='indexerapp.colours')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_colours', to='indexerapp.decoration')),
            ],
            options={
                'verbose_name_plural': 'Decoration Colours',
                'db_table': 'decoration_colours',
            },
        ),
        migrations.CreateModel(
            name='DecorationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.decorationtypes')),
            ],
            options={
                'verbose_name_plural': 'Decoration Types',
                'db_table': 'decoration_types',
            },
        ),
        migrations.AddField(
            model_name='decoration',
            name='decoration_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_subtype', to='indexerapp.decorationtypes'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='decoration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_type', to='indexerapp.decorationtypes'),
        ),
        migrations.CreateModel(
            name='EditionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feast_rubric_sequence', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('subsequence', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bibliography')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_main_function', to='indexerapp.contentfunctions')),
                ('subfunction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sub_function', to='indexerapp.contentfunctions')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.formulas')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='edition_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_edition_index', to='indexerapp.editioncontent'),
        ),
        migrations.AddField(
            model_name='content',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.formulas'),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_genre', to='indexerapp.genre'),
        ),
        migrations.CreateModel(
            name='ImproveOurDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('ms_signature', models.CharField(max_length=1024)),
                ('email', models.EmailField(blank=True, max_length=1024, null=True)),
                ('message', models.TextField()),
                ('changes_made', models.BooleanField(default=False, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_checked_by', to='indexerapp.contributors')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_layers', to='indexerapp.layer'),
        ),
        migrations.AddField(
            model_name='content',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.layer'),
        ),
        migrations.AddField(
            model_name='content',
            name='liturgical_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_genres', to='indexerapp.liturgicalgenres'),
        ),
        migrations.CreateModel(
            name='LiturgicalGenresNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.liturgicalgenres')),
            ],
            options={
                'verbose_name_plural': 'Liturgical Genres Names',
                'db_table': 'liturgical_genres_names',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptMusicNotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_in_ms', models.PositiveIntegerField()),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('original', models.BooleanField(null=True)),
                ('on_lines', models.BooleanField(null=True)),
                ('music_custos', models.BooleanField(null=True)),
                ('number_of_lines', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Music Notations',
                'db_table': 'manuscript_music_notations',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='music_notation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.manuscriptmusicnotations'),
        ),
        migrations.CreateModel(
            name='Manuscripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rism_id', models.CharField(blank=True, max_length=255, null=True)),
                ('foreign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shelf_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('usuarium_shelfmark', models.CharField(blank=True, max_length=255, null=True)),
                ('liturgical_genre_comment', models.TextField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dating_comment', models.TextField(blank=True, null=True)),
                ('place_of_origin_comment', models.TextField(blank=True, null=True)),
                ('how_many_columns_mostly', models.PositiveIntegerField(blank=True, null=True)),
                ('lines_per_page_usually', models.PositiveIntegerField(blank=True, null=True)),
                ('how_many_quires', models.PositiveIntegerField(blank=True, null=True)),
                ('quires_comment', models.TextField(blank=True, null=True)),
                ('foliation_or_pagination', models.CharField(blank=True, choices=[('FOLIATION', 'FOLIATION'), ('PAGINATION', 'PAGINATION')], max_length=12, null=True)),
                ('decorated', models.BooleanField(null=True)),
                ('decoration_comments', models.TextField(blank=True, null=True)),
                ('music_notation', models.BooleanField(null=True)),
                ('music_notation_comments', models.TextField(blank=True, null=True)),
                ('links', models.CharField(blank=True, max_length=1024, null=True)),
                ('additional_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('iiif_manifest_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('pdf_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('general_comment', models.TextField(blank=True, null=True)),
                ('form_of_an_item', models.CharField(blank=True, choices=[('C', 'CODEX'), ('F', 'FRAGMENT'), ('P', 'PALIMPSEST'), ('L', 'LOST ITEM')], max_length=2, null=True)),
                ('connected_ms', models.TextField(blank=True, null=True)),
                ('where_in_connected_ms', models.TextField(blank=True, null=True)),
                ('display_as_main', models.BooleanField(null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('binding_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_binding_place', to='indexerapp.places')),
                ('contemporary_repository_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places')),
                ('place_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_origin', to='indexerapp.places')),
                ('main_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.scriptnames')),
                ('binding_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_binding_date', to='indexerapp.timereference')),
                ('dating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_dating', to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'Manuscripts',
                'db_table': 'manuscripts',
            },
        ),
        migrations.AddField(
            model_name='manuscriptmusicnotations',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_music_notation', to='indexerapp.manuscripts'),
        ),
        migrations.CreateModel(
            name='ManuscriptGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.liturgicalgenres')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_genres', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Genres',
                'db_table': 'manuscript_genres',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptBindingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexerapp.bindingmaterials')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding_materials', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Binding Materials',
                'db_table': 'manuscript_binding_materials',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptBindingDecorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexerapp.bindingdecorationtypes')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding_decorations', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Binding Decorations',
                'db_table': 'manuscript_binding_decorations',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptBindingComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexerapp.bindingcomponents')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding_components', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Binding Components',
                'db_table': 'manuscript_binding_components',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptBibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bibliography')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_bibliography', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Bibliography',
                'db_table': 'manuscript_bibliography',
            },
        ),
        migrations.CreateModel(
            name='Layouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('how_many_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('lines_per_page_maximum', models.PositiveIntegerField(blank=True, null=True)),
                ('lines_per_page_minimum', models.PositiveIntegerField(blank=True, null=True)),
                ('written_space_height_max', models.PositiveIntegerField(blank=True, null=True)),
                ('written_space_width_max', models.PositiveIntegerField(blank=True, null=True)),
                ('ruling_method', models.CharField(blank=True, choices=[('blind-point', 'blind-point'), ('board', 'board'), ('ink', 'ink'), ('lead-point', 'lead-point'), ('rake', 'rake'), ('rake-lead', 'rake (lead-point)'), ('rake-ink', 'rake (ink)'), ('rake-lead-ink', 'rake (lead-point and ink)')], max_length=16, null=True)),
                ('written_above_the_top_line', models.BooleanField(null=True)),
                ('pricking', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('partially', 'partially')], max_length=10, null=True)),
                ('distance_between_horizontal_ruling', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_between_vertical_ruling', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_links', models.CharField(blank=True, max_length=1024, null=True)),
                ('graph_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_layouts', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Layouts',
                'db_table': 'layouts',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='decoration',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_decorations', to='indexerapp.manuscripts'),
        ),
        migrations.AddField(
            model_name='content',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_content', to='indexerapp.manuscripts'),
        ),
        migrations.CreateModel(
            name='Codicology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_parchment_folios', models.IntegerField(blank=True, null=True)),
                ('number_of_paper_leaves', models.IntegerField(blank=True, null=True)),
                ('page_size_max_height', models.PositiveIntegerField(blank=True, null=True)),
                ('page_size_max_width', models.PositiveIntegerField(blank=True, null=True)),
                ('parchment_thickness_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parchment_thickness_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parchment_comment', models.TextField(blank=True, null=True)),
                ('paper_size_max_height', models.PositiveIntegerField(blank=True, null=True)),
                ('paper_size_max_width', models.PositiveIntegerField(blank=True, null=True)),
                ('watermarks', models.BooleanField(null=True)),
                ('foliation_comment', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('parchment_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parchment_colour', to='indexerapp.colours')),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_codicology', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Codicology and Paleography',
                'db_table': 'codicology',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_calendar', to='indexerapp.manuscripts'),
        ),
        migrations.AddField(
            model_name='content',
            name='mass_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mass_hour', to='indexerapp.masshour'),
        ),
        migrations.AddField(
            model_name='manuscriptmusicnotations',
            name='music_notation_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.musicnotationnames'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_projects', to='indexerapp.manuscripts')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.projects')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Projects',
            },
        ),
        migrations.CreateModel(
            name='Quires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_of_the_quire', models.PositiveIntegerField()),
                ('type_of_the_quire', models.CharField(choices=[('bifolium', 'bifolium'), ('binion', 'binion'), ('ternion', 'ternion'), ('quaternion', 'quaternion'), ('quinternion', 'quinternion'), ('seksternion', 'seksternion'), ('septernion', 'septernion'), ('okternion', 'okternion')], max_length=12)),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('graph_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('material', models.CharField(blank=True, choices=[('parchment', 'parchment'), ('paper', 'paper quire')], max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_quires', to='indexerapp.manuscripts')),
            ],
            options={
                'verbose_name_plural': 'Quires',
                'db_table': 'quires',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='quire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.quires'),
        ),
        migrations.CreateModel(
            name='RiteNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('english_translation', models.CharField(blank=True, max_length=128, null=True)),
                ('votive', models.BooleanField(null=True)),
                ('ceremony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ceremony')),
            ],
            options={
                'verbose_name_plural': 'Rite Names Standarized',
                'db_table': 'rite_names',
            },
        ),
        migrations.AddField(
            model_name='editioncontent',
            name='rubric_name_standarized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='rubric_name_standarized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames'),
        ),
        migrations.AddField(
            model_name='content',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='rubric_name_standarized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames'),
        ),
        migrations.AddField(
            model_name='content',
            name='season_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_season_month', to='indexerapp.seasonmonth'),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.sections')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
            },
        ),
        migrations.AddField(
            model_name='ritenames',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.sections'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_main_section', to='indexerapp.sections'),
        ),
        migrations.AddField(
            model_name='content',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sub_section', to='indexerapp.sections'),
        ),
        migrations.CreateModel(
            name='DecorationSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_subjects', to='indexerapp.decoration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_subject', to='indexerapp.subjects')),
            ],
            options={
                'verbose_name_plural': 'Decoration Subjects',
                'db_table': 'decoration_subjects',
            },
        ),
        migrations.CreateModel(
            name='TextStandarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_id', models.CharField(blank=True, max_length=10, null=True)),
                ('cantus_id', models.CharField(blank=True, max_length=10, null=True)),
                ('co_no', models.CharField(blank=True, max_length=10, null=True)),
                ('standard_incipit', models.CharField(blank=True, max_length=64, null=True)),
                ('standard_full_text', models.TextField(blank=True, null=True)),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.formulas')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='text_standarization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.textstandarization'),
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_sequence', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_provenance', to='indexerapp.manuscripts')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places')),
                ('date_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_from', to='indexerapp.timereference')),
                ('date_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_to', to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'Provenance',
                'db_table': 'provenance',
            },
        ),
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origins_comment', models.TextField(blank=True, null=True)),
                ('provenance_comments', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_origins', to='indexerapp.manuscripts')),
                ('origins_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places')),
                ('origins_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'Origins and Datings',
                'db_table': 'origins',
            },
        ),
        migrations.AddField(
            model_name='manuscriptmusicnotations',
            name='dating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference'),
        ),
        migrations.CreateModel(
            name='ManuscriptHands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name_in_ms', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence_in_ms', models.PositiveIntegerField()),
                ('where_in_ms_from', models.CharField(default='', max_length=32)),
                ('where_in_ms_to', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('digital_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_range_interrupted', models.BooleanField(default=False)),
                ('is_medieval', models.BooleanField(null=True)),
                ('is_main_text', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.hands')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_hands', to='indexerapp.manuscripts')),
                ('script_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.scriptnames')),
                ('dating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Hands',
                'db_table': 'manuscript_hands',
            },
        ),
        migrations.AddField(
            model_name='hands',
            name='dating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='date_of_the_addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_dating', to='indexerapp.timereference'),
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.CharField(blank=True, choices=[('very', 'very damaged'), ('average', 'average damaged'), ('slightly', 'slightly damaged')], max_length=10, null=True)),
                ('parchment_shrinkage', models.BooleanField(null=True)),
                ('illegible_text', models.BooleanField(null=True)),
                ('ink_corrosion', models.BooleanField(null=True)),
                ('copper_corrosion', models.BooleanField(null=True)),
                ('powdering_or_cracking_paint_layer', models.BooleanField(null=True)),
                ('conservation', models.BooleanField(null=True)),
                ('darkening', models.BooleanField(null=True)),
                ('water_staining', models.BooleanField(null=True)),
                ('historic_repairs', models.BooleanField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_condition', to='indexerapp.manuscripts')),
                ('conservation_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_conservation_dating', to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'Condition',
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='Clla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clla_no', models.CharField(blank=True, max_length=255, null=True)),
                ('liturgical_genre', models.CharField(blank=True, max_length=512, null=True)),
                ('dating_comment', models.TextField(blank=True, null=True)),
                ('provenance', models.CharField(blank=True, max_length=512, null=True)),
                ('provenance_comment', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, default='Klaus Gamber', max_length=128, null=True)),
                ('data_contributor', models.CharField(blank=True, default='Quirin Rosenberger', max_length=512, null=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_clla', to='indexerapp.manuscripts')),
                ('dating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_dating', to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'CLLA',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='date_of_the_addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_addition_dating', to='indexerapp.timereference'),
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_height', models.PositiveIntegerField(blank=True, null=True)),
                ('max_width', models.PositiveIntegerField(blank=True, null=True)),
                ('block_max', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('original', 'original'), ('early', 'early modern'), ('historical', 'historical rebinding'), ('conservation', 'conservation binding'), ('restored', 'restored binding')], max_length=12, null=True)),
                ('decoration_comment', models.TextField(blank=True, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('characteristic_of_components', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('style_of_binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bindingstyles')),
                ('type_of_binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bindingtypes')),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding', to='indexerapp.manuscripts')),
                ('place_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places')),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference')),
            ],
            options={
                'verbose_name_plural': 'Bindings',
                'db_table': 'bindings',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('votive', models.BooleanField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.topic')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.sections')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='ContentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_topics', to='indexerapp.content')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_contents', to='indexerapp.topic')),
            ],
            options={
                'verbose_name': 'Content Topic',
                'verbose_name_plural': 'Content Topics',
                'db_table': 'content_topics',
            },
        ),
        migrations.CreateModel(
            name='Traditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_rgb', models.CharField(blank=True, max_length=8, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.liturgicalgenres')),
            ],
            options={
                'verbose_name_plural': 'Traditions',
                'db_table': 'traditions',
            },
        ),
        migrations.AddField(
            model_name='formulas',
            name='tradition',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_traditions', to='indexerapp.traditions'),
        ),
        migrations.AddField(
            model_name='seasonmonth',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_types', to='indexerapp.type'),
        ),
        migrations.AddField(
            model_name='masshour',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.type'),
        ),
        migrations.AddField(
            model_name='genre',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_types', to='indexerapp.type'),
        ),
        migrations.AddField(
            model_name='day',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_types', to='indexerapp.type'),
        ),
        migrations.CreateModel(
            name='UserOpenAIAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users OpenAI API Keys',
                'db_table': 'user_openai_api_key',
            },
        ),
        migrations.CreateModel(
            name='Watermarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('watermark_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='indexerapp.contributors')),
                ('data_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors')),
            ],
            options={
                'verbose_name_plural': 'Watermarks',
                'db_table': 'watermarks',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptWatermarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_in_manuscript', models.CharField(max_length=255)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_watermarks', to='indexerapp.manuscripts')),
                ('watermark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.watermarks')),
            ],
            options={
                'verbose_name_plural': 'Manuscript Watermarks',
                'db_table': 'manuscript_watermarks',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('types', models.ManyToManyField(blank=True, related_name='%(class)s_types', to='indexerapp.type')),
            ],
            options={
                'verbose_name_plural': 'Weeks',
                'db_table': 'week',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_week', to='indexerapp.week'),
        ),
    ]
