# Generated by Django 6.0.3 on 2026-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='binding',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingcomponents',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bindingcomponents',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingdecorationtypes',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bindingdecorationtypes',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingmaterials',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bindingmaterials',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingstyles',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bindingstyles',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingtypes',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bindingtypes',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='clla',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clla',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='codicology',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='colours',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colours',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contentfunctions',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contentfunctions',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contenttopic',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contenttopic',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contributors',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contributors',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contributors',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='day',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='day',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decoration',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decorationcharacteristics',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='decorationcharacteristics',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decorationcolours',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='decorationcolours',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decorationsubjects',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='decorationsubjects',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decorationtechniques',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='decorationtechniques',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decorationtypes',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='decorationtypes',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='editioncontent',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='feastranks',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feastranks',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formulas',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hands',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hands',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hands',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='layouts',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='liturgicalgenres',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liturgicalgenres',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='liturgicalgenresnames',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liturgicalgenresnames',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptbibliography',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscriptbibliography',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptbindingcomponents',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscriptbindingcomponents',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptbindingdecorations',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscriptbindingdecorations',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptbindingmaterials',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscriptbindingmaterials',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptgenres',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscriptgenres',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscripthands',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptmusicnotations',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='sync_status',
            field=models.CharField(choices=[('in_preparation', 'in preparation'), ('ready', 'ready'), ('synchronized', 'synchronized'), ('updated', 'updated'), ('deleted', 'deleted')], default='in_preparation', max_length=20),
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptwatermarks',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscriptwatermarks',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='masshour',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='masshour',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='musicnotationnames',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musicnotationnames',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='origins',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='places',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='provenance',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quires',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ritenames',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ritenames',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptnames',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scriptnames',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonmonth',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seasonmonth',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='textstandarization',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='textstandarization',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='timereference',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timereference',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='traditions',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traditions',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='type',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='watermarks',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='watermarks',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='week',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='week',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=16)),
                ('object_uuid', models.UUIDField(db_index=True)),
                ('source_pk', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ETL Deleted Record',
                'verbose_name_plural': 'ETL Deleted Records',
                'db_table': 'etl_deleted_records',
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_uuid'), name='etl_deleted_records_model_uuid_uniq')],
            },
        ),
    ]
