# Generated by Django 6.0.3 on 2026-03-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0002_bibliography_entry_date_bibliography_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msprojects',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='msprojects',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
