# Generated by Django 6.0.3 on 2026-05-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0006_binding_manuscript_uuid_calendar_content_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='msprojects',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='msprojects',
            name='project_uuid',
            field=models.ForeignKey(blank=True, db_column='project_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.projects', to_field='uuid'),
        ),
        migrations.AddConstraint(
            model_name='manuscripts',
            constraint=models.UniqueConstraint(fields=('uuid',), name='uq_manuscripts_uuid'),
        ),
        migrations.AddConstraint(
            model_name='projects',
            constraint=models.UniqueConstraint(fields=('uuid',), name='uq_projects_uuid'),
        ),
    ]
