# Generated by Django 6.0.3 on 2026-05-06 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0007_projects_icon_projects_project_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedebate',
            name='object_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributedebate',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binding',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='clla',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbibliography',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingcomponents',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingdecorations',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingmaterials',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptwatermarks',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='quires',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
    ]
