# Generated by Django 6.0.3 on 2026-05-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0009_alter_calendar_uuid_alter_characteristics_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='content_uuid',
            field=models.ForeignKey(blank=True, db_column='content_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.content', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_of_the_addition_uuid',
            field=models.ForeignKey(blank=True, db_column='date_of_the_addition_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='feast_rank_uuid',
            field=models.ForeignKey(blank=True, db_column='feast_rank_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.feastranks', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='day_uuid',
            field=models.ForeignKey(blank=True, db_column='day_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.day', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='edition_index_uuid',
            field=models.ForeignKey(blank=True, db_column='edition_index_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.editioncontent', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='function_uuid',
            field=models.ForeignKey(blank=True, db_column='function_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.genre', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='layer_uuid',
            field=models.ForeignKey(blank=True, db_column='layer_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.layer', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='liturgical_genre_uuid',
            field=models.ForeignKey(blank=True, db_column='liturgical_genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='mass_hour_uuid',
            field=models.ForeignKey(blank=True, db_column='mass_hour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.masshour', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='music_notation_uuid',
            field=models.ForeignKey(blank=True, db_column='music_notation_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscriptmusicnotations', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='quire_uuid',
            field=models.ForeignKey(blank=True, db_column='quire_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.quires', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='rubric_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='season_month_uuid',
            field=models.ForeignKey(blank=True, db_column='season_month_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.seasonmonth', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subfunction_uuid',
            field=models.ForeignKey(blank=True, db_column='subfunction_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subsection_uuid',
            field=models.ForeignKey(blank=True, db_column='subsection_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_standarization_uuid',
            field=models.ForeignKey(blank=True, db_column='text_standarization_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.textstandarization', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='week_uuid',
            field=models.ForeignKey(blank=True, db_column='week_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.week', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='calendar_uuid',
            field=models.ForeignKey(blank=True, db_column='calendar_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.calendar', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='content_uuid',
            field=models.ForeignKey(blank=True, db_column='content_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.content', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='date_of_the_addition_uuid',
            field=models.ForeignKey(blank=True, db_column='date_of_the_addition_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_subtype_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_subtype_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_type_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_type_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='technique_uuid',
            field=models.ForeignKey(blank=True, db_column='technique_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.decorationtechniques', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcharacteristics',
            name='characteristics_uuid',
            field=models.ForeignKey(blank=True, db_column='characteristics_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.characteristics', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcharacteristics',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.decoration', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcolours',
            name='colour_uuid',
            field=models.ForeignKey(blank=True, db_column='colour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcolours',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.decoration', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationsubjects',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.decoration', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationsubjects',
            name='subject_uuid',
            field=models.ForeignKey(blank=True, db_column='subject_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.subjects', to_field='uuid'),
        ),
    ]
