# Generated by Django 6.0.3 on 2026-05-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0011_alter_bibliography_uuid_alter_bindingcomponents_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='date_uuid',
            field=models.ForeignKey(blank=True, db_column='date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='place_of_origin_uuid',
            field=models.ForeignKey(blank=True, db_column='place_of_origin_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='style_of_binding_uuid',
            field=models.ForeignKey(blank=True, db_column='style_of_binding_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.bindingstyles', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='type_of_binding_uuid',
            field=models.ForeignKey(blank=True, db_column='type_of_binding_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.bindingtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='clla',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='parchment_colour_uuid',
            field=models.ForeignKey(blank=True, db_column='parchment_colour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='conservation_date_uuid',
            field=models.ForeignKey(blank=True, db_column='conservation_date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='contentfunctions',
            name='parent_function_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_function_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='contenttopic',
            name='content_uuid',
            field=models.ForeignKey(blank=True, db_column='content_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.content', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='contenttopic',
            name='topic_uuid',
            field=models.ForeignKey(blank=True, db_column='topic_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.topic', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='bibliography_uuid',
            field=models.ForeignKey(blank=True, db_column='bibliography_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.bibliography', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='function_uuid',
            field=models.ForeignKey(blank=True, db_column='function_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='subfunction_uuid',
            field=models.ForeignKey(blank=True, db_column='subfunction_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='hands',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='liturgicalgenresnames',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbibliography',
            name='bibliography_uuid',
            field=models.ForeignKey(blank=True, db_column='bibliography_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.bibliography', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingcomponents',
            name='component_uuid',
            field=models.ForeignKey(blank=True, db_column='component_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.bindingcomponents', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingdecorations',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.bindingdecorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingmaterials',
            name='material_uuid',
            field=models.ForeignKey(blank=True, db_column='material_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.bindingmaterials', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptgenres',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptgenres',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='hand_uuid',
            field=models.ForeignKey(blank=True, db_column='hand_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.hands', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='script_name_uuid',
            field=models.ForeignKey(blank=True, db_column='script_name_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.scriptnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='music_notation_name_uuid',
            field=models.ForeignKey(blank=True, db_column='music_notation_name_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.musicnotationnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='binding_date_uuid',
            field=models.ForeignKey(blank=True, db_column='binding_date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='binding_place_uuid',
            field=models.ForeignKey(blank=True, db_column='binding_place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='contemporary_repository_place_uuid',
            field=models.ForeignKey(blank=True, db_column='contemporary_repository_place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='main_script_uuid',
            field=models.ForeignKey(blank=True, db_column='main_script_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.scriptnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='place_of_origin_uuid',
            field=models.ForeignKey(blank=True, db_column='place_of_origin_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptwatermarks',
            name='watermark_uuid',
            field=models.ForeignKey(blank=True, db_column='watermark_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.watermarks', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='masshour',
            name='type_uuid',
            field=models.ForeignKey(blank=True, db_column='type_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.type', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='origins_date_uuid',
            field=models.ForeignKey(blank=True, db_column='origins_date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='origins_place_uuid',
            field=models.ForeignKey(blank=True, db_column='origins_place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='date_from_uuid',
            field=models.ForeignKey(blank=True, db_column='date_from_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='date_to_uuid',
            field=models.ForeignKey(blank=True, db_column='date_to_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='place_uuid',
            field=models.ForeignKey(blank=True, db_column='place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='quires',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='ritenames',
            name='ceremony_uuid',
            field=models.ForeignKey(blank=True, db_column='ceremony_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.ceremony', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='ritenames',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='textstandarization',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.topic', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='traditions',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='watermarks',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexerapp.contributors', to_field='uuid'),
        ),
    ]
