# Generated by Django 6.0.3 on 2026-05-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0012_alter_binding_data_contributor_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='parent_colour_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_colour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationtypes',
            name='parent_type_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_type_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='parent_section_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indexerapp.sections', to_field='uuid'),
        ),
    ]
