# Generated by Django 6.0.3 on 2026-05-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0013_alter_colours_parent_colour_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributedebate',
            name='object_id',
        ),
    ]
