# Generated by Django 6.0.3 on 2026-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0014_remove_attributedebate_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedebate',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
