# Generated by Django 6.0.3 on 2026-05-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0015_attributedebate_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscriptgenres',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='manuscriptgenres',
            name='manuscript',
        ),
        migrations.AlterField(
            model_name='manuscriptgenres',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_genres', to='indexerapp.manuscripts', to_field='uuid'),
        ),
    ]
