# Generated by Django 6.0.3 on 2026-05-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0016_remove_manuscriptgenres_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binding',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='binding',
            name='date',
        ),
        migrations.RemoveField(
            model_name='binding',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='binding',
            name='place_of_origin',
        ),
        migrations.RemoveField(
            model_name='binding',
            name='style_of_binding',
        ),
        migrations.RemoveField(
            model_name='binding',
            name='type_of_binding',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='content',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='date_of_the_addition',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='feast_rank',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='rubric_name_standarized',
        ),
        migrations.RemoveField(
            model_name='clla',
            name='dating',
        ),
        migrations.RemoveField(
            model_name='clla',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='codicology',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='codicology',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='codicology',
            name='parchment_colour',
        ),
        migrations.RemoveField(
            model_name='colours',
            name='parent_colour',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='conservation_date',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='content',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='content',
            name='day',
        ),
        migrations.RemoveField(
            model_name='content',
            name='edition_index',
        ),
        migrations.RemoveField(
            model_name='content',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='content',
            name='function',
        ),
        migrations.RemoveField(
            model_name='content',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='content',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='content',
            name='liturgical_genre',
        ),
        migrations.RemoveField(
            model_name='content',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='content',
            name='mass_hour',
        ),
        migrations.RemoveField(
            model_name='content',
            name='music_notation',
        ),
        migrations.RemoveField(
            model_name='content',
            name='quire',
        ),
        migrations.RemoveField(
            model_name='content',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='content',
            name='season_month',
        ),
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subfunction',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subsection',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text_standarization',
        ),
        migrations.RemoveField(
            model_name='content',
            name='week',
        ),
        migrations.RemoveField(
            model_name='contentfunctions',
            name='parent_function',
        ),
        migrations.RemoveField(
            model_name='contenttopic',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contenttopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='content',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='date_of_the_addition',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='decoration_subtype',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='decoration_type',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='rubric_name_standarized',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='decorationcharacteristics',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='decorationcharacteristics',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='decorationcolours',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='decorationcolours',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='decorationsubjects',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='decorationsubjects',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='decorationtypes',
            name='parent_type',
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='bibliography',
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='function',
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='rubric_name_standarized',
        ),
        migrations.RemoveField(
            model_name='editioncontent',
            name='subfunction',
        ),
        migrations.RemoveField(
            model_name='hands',
            name='dating',
        ),
        migrations.RemoveField(
            model_name='image',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='layouts',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='layouts',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='liturgicalgenresnames',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='manuscriptbibliography',
            name='bibliography',
        ),
        migrations.RemoveField(
            model_name='manuscriptbibliography',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptbindingcomponents',
            name='component',
        ),
        migrations.RemoveField(
            model_name='manuscriptbindingcomponents',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptbindingdecorations',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='manuscriptbindingdecorations',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptbindingmaterials',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptbindingmaterials',
            name='material',
        ),
        migrations.RemoveField(
            model_name='manuscripthands',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='manuscripthands',
            name='dating',
        ),
        migrations.RemoveField(
            model_name='manuscripthands',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='manuscripthands',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscripthands',
            name='script_name',
        ),
        migrations.RemoveField(
            model_name='manuscriptmusicnotations',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='manuscriptmusicnotations',
            name='dating',
        ),
        migrations.RemoveField(
            model_name='manuscriptmusicnotations',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptmusicnotations',
            name='music_notation_name',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='binding_date',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='binding_place',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='contemporary_repository_place',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='dating',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='main_script',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='place_of_origin',
        ),
        migrations.RemoveField(
            model_name='manuscriptwatermarks',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptwatermarks',
            name='watermark',
        ),
        migrations.RemoveField(
            model_name='masshour',
            name='type',
        ),
        migrations.RemoveField(
            model_name='msprojects',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='msprojects',
            name='project',
        ),
        migrations.RemoveField(
            model_name='origins',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='origins',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='origins',
            name='origins_date',
        ),
        migrations.RemoveField(
            model_name='origins',
            name='origins_place',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='place',
        ),
        migrations.RemoveField(
            model_name='quires',
            name='data_contributor',
        ),
        migrations.RemoveField(
            model_name='quires',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='ritenames',
            name='ceremony',
        ),
        migrations.RemoveField(
            model_name='ritenames',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='parent_section',
        ),
        migrations.RemoveField(
            model_name='textstandarization',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='section',
        ),
        migrations.RemoveField(
            model_name='traditions',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='watermarks',
            name='data_contributor',
        ),
        migrations.AlterField(
            model_name='binding',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='date_uuid',
            field=models.ForeignKey(blank=True, db_column='date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='place_of_origin_uuid',
            field=models.ForeignKey(blank=True, db_column='place_of_origin_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='style_of_binding_uuid',
            field=models.ForeignKey(blank=True, db_column='style_of_binding_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bindingstyles', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='type_of_binding_uuid',
            field=models.ForeignKey(blank=True, db_column='type_of_binding_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bindingtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='content_uuid',
            field=models.ForeignKey(blank=True, db_column='content_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_content', to='indexerapp.content', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_of_the_addition_uuid',
            field=models.ForeignKey(blank=True, db_column='date_of_the_addition_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_addition_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='feast_rank_uuid',
            field=models.ForeignKey(blank=True, db_column='feast_rank_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_feast', to='indexerapp.feastranks', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_calendar', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='clla',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='clla',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_clla', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_codicology', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='parchment_colour_uuid',
            field=models.ForeignKey(blank=True, db_column='parchment_colour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parchment_colour', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='colours',
            name='parent_colour_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_colour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='conservation_date_uuid',
            field=models.ForeignKey(blank=True, db_column='conservation_date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_conservation_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_condition', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='day_uuid',
            field=models.ForeignKey(blank=True, db_column='day_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_day', to='indexerapp.day', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='edition_index_uuid',
            field=models.ForeignKey(blank=True, db_column='edition_index_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_edition_index', to='indexerapp.editioncontent', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='function_uuid',
            field=models.ForeignKey(blank=True, db_column='function_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_main_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_genre', to='indexerapp.genre', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='layer_uuid',
            field=models.ForeignKey(blank=True, db_column='layer_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.layer', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='liturgical_genre_uuid',
            field=models.ForeignKey(blank=True, db_column='liturgical_genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_genres', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_content', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='mass_hour_uuid',
            field=models.ForeignKey(blank=True, db_column='mass_hour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mass_hour', to='indexerapp.masshour', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='music_notation_uuid',
            field=models.ForeignKey(blank=True, db_column='music_notation_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.manuscriptmusicnotations', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='quire_uuid',
            field=models.ForeignKey(blank=True, db_column='quire_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.quires', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='rubric_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='season_month_uuid',
            field=models.ForeignKey(blank=True, db_column='season_month_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_season_month', to='indexerapp.seasonmonth', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_main_section', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subfunction_uuid',
            field=models.ForeignKey(blank=True, db_column='subfunction_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sub_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subsection_uuid',
            field=models.ForeignKey(blank=True, db_column='subsection_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sub_section', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_standarization_uuid',
            field=models.ForeignKey(blank=True, db_column='text_standarization_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.textstandarization', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='week_uuid',
            field=models.ForeignKey(blank=True, db_column='week_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_week', to='indexerapp.week', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='contentfunctions',
            name='parent_function_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_function_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='contenttopic',
            name='content_uuid',
            field=models.ForeignKey(blank=True, db_column='content_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_topics', to='indexerapp.content', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='contenttopic',
            name='topic_uuid',
            field=models.ForeignKey(blank=True, db_column='topic_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_contents', to='indexerapp.topic', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='calendar_uuid',
            field=models.ForeignKey(blank=True, db_column='calendar_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_decoration', to='indexerapp.calendar', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='content_uuid',
            field=models.ForeignKey(blank=True, db_column='content_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_decoration', to='indexerapp.content', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='date_of_the_addition_uuid',
            field=models.ForeignKey(blank=True, db_column='date_of_the_addition_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_subtype_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_subtype_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_subtype', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_type_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_type_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_type', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_decorations', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='technique_uuid',
            field=models.ForeignKey(blank=True, db_column='technique_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_technique', to='indexerapp.decorationtechniques', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcharacteristics',
            name='characteristics_uuid',
            field=models.ForeignKey(blank=True, db_column='characteristics_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_characteristics', to='indexerapp.characteristics', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcharacteristics',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_characteristics', to='indexerapp.decoration', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcolours',
            name='colour_uuid',
            field=models.ForeignKey(blank=True, db_column='colour_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_colour', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcolours',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_colours', to='indexerapp.decoration', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationsubjects',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_subjects', to='indexerapp.decoration', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationsubjects',
            name='subject_uuid',
            field=models.ForeignKey(blank=True, db_column='subject_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decoration_subject', to='indexerapp.subjects', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationtypes',
            name='parent_type_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_type_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='bibliography_uuid',
            field=models.ForeignKey(blank=True, db_column='bibliography_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bibliography', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='function_uuid',
            field=models.ForeignKey(blank=True, db_column='function_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_main_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='subfunction_uuid',
            field=models.ForeignKey(blank=True, db_column='subfunction_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sub_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='hands',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='image',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_layouts', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='liturgicalgenresnames',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbibliography',
            name='bibliography_uuid',
            field=models.ForeignKey(blank=True, db_column='bibliography_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.bibliography', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbibliography',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_bibliography', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingcomponents',
            name='component_uuid',
            field=models.ForeignKey(blank=True, db_column='component_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.bindingcomponents', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingcomponents',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding_components', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingdecorations',
            name='decoration_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.bindingdecorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingdecorations',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding_decorations', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingmaterials',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_binding_materials', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbindingmaterials',
            name='material_uuid',
            field=models.ForeignKey(blank=True, db_column='material_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.bindingmaterials', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='hand_uuid',
            field=models.ForeignKey(blank=True, db_column='hand_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.hands', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_hands', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='script_name_uuid',
            field=models.ForeignKey(blank=True, db_column='script_name_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.scriptnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_music_notation', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='music_notation_name_uuid',
            field=models.ForeignKey(blank=True, db_column='music_notation_name_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.musicnotationnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='binding_date_uuid',
            field=models.ForeignKey(blank=True, db_column='binding_date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_binding_date', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='binding_place_uuid',
            field=models.ForeignKey(blank=True, db_column='binding_place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_binding_place', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='contemporary_repository_place_uuid',
            field=models.ForeignKey(blank=True, db_column='contemporary_repository_place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='main_script_uuid',
            field=models.ForeignKey(blank=True, db_column='main_script_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.scriptnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='place_of_origin_uuid',
            field=models.ForeignKey(blank=True, db_column='place_of_origin_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_origin', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptwatermarks',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_watermarks', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptwatermarks',
            name='watermark_uuid',
            field=models.ForeignKey(blank=True, db_column='watermark_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.watermarks', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='masshour',
            name='type_uuid',
            field=models.ForeignKey(blank=True, db_column='type_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.type', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='msprojects',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_projects', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='msprojects',
            name='project_uuid',
            field=models.ForeignKey(blank=True, db_column='project_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.projects', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_origins', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='origins_date_uuid',
            field=models.ForeignKey(blank=True, db_column='origins_date_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='origins_place_uuid',
            field=models.ForeignKey(blank=True, db_column='origins_place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='date_from_uuid',
            field=models.ForeignKey(blank=True, db_column='date_from_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_from', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='date_to_uuid',
            field=models.ForeignKey(blank=True, db_column='date_to_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_to', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_provenance', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='place_uuid',
            field=models.ForeignKey(blank=True, db_column='place_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='quires',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='quires',
            name='manuscript_uuid',
            field=models.ForeignKey(blank=True, db_column='manuscript_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ms_quires', to='indexerapp.manuscripts', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='ritenames',
            name='ceremony_uuid',
            field=models.ForeignKey(blank=True, db_column='ceremony_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.ceremony', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='ritenames',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='parent_section_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='textstandarization',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent_uuid',
            field=models.ForeignKey(blank=True, db_column='parent_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexerapp.topic', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='traditions',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='watermarks',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
    ]
