# Generated by Django 6.0.3 on 2026-07-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0019_enforce_uuid_fk_referential_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='date_uuid',
            field=models.ForeignKey(blank=True, db_column='date_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='place_of_origin_uuid',
            field=models.ForeignKey(blank=True, db_column='place_of_origin_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='style_of_binding_uuid',
            field=models.ForeignKey(blank=True, db_column='style_of_binding_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.bindingstyles', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='binding',
            name='type_of_binding_uuid',
            field=models.ForeignKey(blank=True, db_column='type_of_binding_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.bindingtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_of_the_addition_uuid',
            field=models.ForeignKey(blank=True, db_column='date_of_the_addition_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_addition_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='feast_rank_uuid',
            field=models.ForeignKey(blank=True, db_column='feast_rank_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_feast', to='indexerapp.feastranks', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='clla',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='codicology',
            name='parchment_colour_uuid',
            field=models.ForeignKey(blank=True, db_column='parchment_colour_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parchment_colour', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='conservation_date_uuid',
            field=models.ForeignKey(blank=True, db_column='conservation_date_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_conservation_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='day_uuid',
            field=models.ForeignKey(blank=True, db_column='day_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_day', to='indexerapp.day', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='edition_index_uuid',
            field=models.ForeignKey(blank=True, db_column='edition_index_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_edition_index', to='indexerapp.editioncontent', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='function_uuid',
            field=models.ForeignKey(blank=True, db_column='function_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_main_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_genre', to='indexerapp.genre', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='layer_uuid',
            field=models.ForeignKey(blank=True, db_column='layer_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.layer', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='liturgical_genre_uuid',
            field=models.ForeignKey(blank=True, db_column='liturgical_genre_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_genres', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='mass_hour_uuid',
            field=models.ForeignKey(blank=True, db_column='mass_hour_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_mass_hour', to='indexerapp.masshour', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='rubric_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='season_month_uuid',
            field=models.ForeignKey(blank=True, db_column='season_month_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_season_month', to='indexerapp.seasonmonth', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_main_section', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subfunction_uuid',
            field=models.ForeignKey(blank=True, db_column='subfunction_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sub_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subsection_uuid',
            field=models.ForeignKey(blank=True, db_column='subsection_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sub_section', to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_standarization_uuid',
            field=models.ForeignKey(blank=True, db_column='text_standarization_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.textstandarization', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='content',
            name='week_uuid',
            field=models.ForeignKey(blank=True, db_column='week_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_week', to='indexerapp.week', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='date_of_the_addition_uuid',
            field=models.ForeignKey(blank=True, db_column='date_of_the_addition_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_subtype_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_subtype_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_subtype', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_type_uuid',
            field=models.ForeignKey(blank=True, db_column='decoration_type_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_type', to='indexerapp.decorationtypes', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='technique_uuid',
            field=models.ForeignKey(blank=True, db_column='technique_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_technique', to='indexerapp.decorationtechniques', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcharacteristics',
            name='characteristics_uuid',
            field=models.ForeignKey(blank=True, db_column='characteristics_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_characteristics', to='indexerapp.characteristics', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationcolours',
            name='colour_uuid',
            field=models.ForeignKey(blank=True, db_column='colour_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_colour', to='indexerapp.colours', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='decorationsubjects',
            name='subject_uuid',
            field=models.ForeignKey(blank=True, db_column='subject_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoration_subject', to='indexerapp.subjects', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='bibliography_uuid',
            field=models.ForeignKey(blank=True, db_column='bibliography_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.bibliography', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='function_uuid',
            field=models.ForeignKey(blank=True, db_column='function_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_main_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='rubric_name_standarized_uuid',
            field=models.ForeignKey(blank=True, db_column='rubric_name_standarized_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.ritenames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='editioncontent',
            name='subfunction_uuid',
            field=models.ForeignKey(blank=True, db_column='subfunction_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sub_function', to='indexerapp.contentfunctions', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='hands',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='liturgicalgenresnames',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptbibliography',
            name='bibliography_uuid',
            field=models.ForeignKey(blank=True, db_column='bibliography_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.bibliography', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptgenres',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='hand_uuid',
            field=models.ForeignKey(blank=True, db_column='hand_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.hands', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripthands',
            name='script_name_uuid',
            field=models.ForeignKey(blank=True, db_column='script_name_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.scriptnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptmusicnotations',
            name='music_notation_name_uuid',
            field=models.ForeignKey(blank=True, db_column='music_notation_name_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.musicnotationnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='binding_date_uuid',
            field=models.ForeignKey(blank=True, db_column='binding_date_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_binding_date', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='binding_place_uuid',
            field=models.ForeignKey(blank=True, db_column='binding_place_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_binding_place', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='contemporary_repository_place_uuid',
            field=models.ForeignKey(blank=True, db_column='contemporary_repository_place_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='dating_uuid',
            field=models.ForeignKey(blank=True, db_column='dating_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_dating', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='main_script_uuid',
            field=models.ForeignKey(blank=True, db_column='main_script_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.scriptnames', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='place_of_origin_uuid',
            field=models.ForeignKey(blank=True, db_column='place_of_origin_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_origin', to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='manuscriptwatermarks',
            name='watermark_uuid',
            field=models.ForeignKey(blank=True, db_column='watermark_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.watermarks', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='masshour',
            name='type_uuid',
            field=models.ForeignKey(blank=True, db_column='type_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.type', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='msprojects',
            name='project_uuid',
            field=models.ForeignKey(blank=True, db_column='project_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.projects', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='origins_date_uuid',
            field=models.ForeignKey(blank=True, db_column='origins_date_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='origins_place_uuid',
            field=models.ForeignKey(blank=True, db_column='origins_place_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='date_from_uuid',
            field=models.ForeignKey(blank=True, db_column='date_from_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_from', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='date_to_uuid',
            field=models.ForeignKey(blank=True, db_column='date_to_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_to', to='indexerapp.timereference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='place_uuid',
            field=models.ForeignKey(blank=True, db_column='place_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.places', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='quires',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='ritenames',
            name='ceremony_uuid',
            field=models.ForeignKey(blank=True, db_column='ceremony_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.ceremony', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='ritenames',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='textstandarization',
            name='formula_uuid',
            field=models.ForeignKey(blank=True, db_column='formula_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.formulas', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section_uuid',
            field=models.ForeignKey(blank=True, db_column='section_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.sections', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='traditions',
            name='genre_uuid',
            field=models.ForeignKey(blank=True, db_column='genre_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='indexerapp.liturgicalgenres', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='watermarks',
            name='data_contributor_uuid',
            field=models.ForeignKey(blank=True, db_column='data_contributor_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_contributors', to='indexerapp.contributors', to_field='uuid'),
        ),
    ]
