# Generated by Django 6.0.3 on 2026-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0020_protect_dictionary_fk_deletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscripts',
            name='binding_place_unsure',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='place_of_origin_unsure',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='origins',
            name='unsure',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='provenance',
            name='unsure',
            field=models.BooleanField(null=True),
        ),
    ]
