# Generated by Django 6.0.3 on 2026-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0021_manuscripts_binding_place_unsure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_type',
            field=models.CharField(blank=True, choices=[('library', 'library'), ('center', 'center'), ('scriptory', 'scriptory'), ('multiple', 'multiple'), ('current repository', 'current repository'), ('historical institution', 'historical institution'), ('region', 'region'), ('city', 'city'), ('diocese', 'diocese')], max_length=32, null=True),
        ),
    ]
