# Generated by Django 6.0.3 on 2026-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexerapp', '0022_places_place_type_choices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bindingcomponents',
            constraint=models.UniqueConstraint(fields=('name',), name='bindingcomponents_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bindingdecorationtypes',
            constraint=models.UniqueConstraint(fields=('name',), name='bindingdecorationtypes_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bindingmaterials',
            constraint=models.UniqueConstraint(fields=('name',), name='bindingmaterials_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bindingstyles',
            constraint=models.UniqueConstraint(fields=('name',), name='bindingstyles_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bindingtypes',
            constraint=models.UniqueConstraint(fields=('name',), name='bindingtypes_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ceremony',
            constraint=models.UniqueConstraint(fields=('name',), name='ceremony_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='characteristics',
            constraint=models.UniqueConstraint(fields=('name',), name='characteristics_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='colours',
            constraint=models.UniqueConstraint(fields=('name',), name='colours_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='colours',
            constraint=models.UniqueConstraint(fields=('rgb',), name='colours_rgb_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contentfunctions',
            constraint=models.UniqueConstraint(fields=('name',), name='contentfunctions_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('short_name',), name='day_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('name',), name='day_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='decorationtechniques',
            constraint=models.UniqueConstraint(fields=('name',), name='decorationtechniques_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='decorationtypes',
            constraint=models.UniqueConstraint(fields=('name',), name='decorationtypes_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='feastranks',
            constraint=models.UniqueConstraint(fields=('name',), name='feastranks_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('short_name',), name='genre_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('name',), name='genre_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('short_name',), name='layer_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('name',), name='layer_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='liturgicalgenres',
            constraint=models.UniqueConstraint(fields=('title',), name='liturgicalgenres_title_uniq'),
        ),
        migrations.AddConstraint(
            model_name='masshour',
            constraint=models.UniqueConstraint(fields=('short_name',), name='masshour_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='masshour',
            constraint=models.UniqueConstraint(fields=('name',), name='masshour_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='musicnotationnames',
            constraint=models.UniqueConstraint(fields=('name',), name='musicnotationnames_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projects',
            constraint=models.UniqueConstraint(fields=('name',), name='projects_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ritenames',
            constraint=models.UniqueConstraint(fields=('name',), name='ritenames_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scriptnames',
            constraint=models.UniqueConstraint(fields=('name',), name='scriptnames_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='seasonmonth',
            constraint=models.UniqueConstraint(fields=('short_name',), name='seasonmonth_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='seasonmonth',
            constraint=models.UniqueConstraint(fields=('name',), name='seasonmonth_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('name',), name='sections_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subjects',
            constraint=models.UniqueConstraint(fields=('name',), name='subjects_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='textstandarization',
            constraint=models.UniqueConstraint(fields=('usu_id',), name='textstandarization_usu_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='textstandarization',
            constraint=models.UniqueConstraint(fields=('standard_incipit',), name='textstandarization_standard_incipit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timereference',
            constraint=models.UniqueConstraint(fields=('time_description',), name='timereference_time_description_uniq'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('name',), name='topic_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='traditions',
            constraint=models.UniqueConstraint(fields=('name',), name='traditions_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('short_name',), name='type_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('name',), name='type_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('short_name',), name='week_short_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('name',), name='week_name_uniq'),
        ),
    ]
